### ISSUE TITLE
Marketing website

### ISSUE THREAD

**Issue by singpolyma** [usetint/tint#138]
https://github.com/usetint/usetint.github.io

**Comment by singpolyma** [comment]
@ericroberts I think we should make a repo under usetint for this, and we can use it for testing some of the Github integration stuff, etc, more easily.  What should we call it?  Just "website" ?

**Comment by ericroberts** [comment]
@singpolyma website sounds good to me.

**Comment by singpolyma** [comment]
Closing this in favour of tracking on https://github.com/usetint/usetint.github.io/issues
