### ISSUE TITLE
Cannot open a YML file that has a root element of an array

### ISSUE THREAD

**Issue by ericroberts** [usetint/tint#274]

**Comment by ericroberts** [comment]
@singpolyma I've determined the cause of this issue. It is due to the recent changes that parsed frontmatter from the filename.

What happens currently is that the code extracts frontmatter from the filename (a date for example) and creates a hash of that data. It then tries to merge in data parsed from the file itself, which is an array, and so the error happens.

If there were no frontmatter parsed from the filename, the issue is simple, just return the data parsed from the document. But it's not immediately obvious to me what we should do when there is frontmatter from the filename and the contents of the file is an array. Any thoughts?

**Comment by singpolyma** [comment]
@ericroberts hmm.  that's a pickle indeed.  I can think of a few options:

1. Just return the contents of the document -- no filename frontmatter allowed
2. Always ignore filename frontmatter on YML files which don't really have "frontmatter"
3. Make filename frontmatter combined with a root array an error of some kind (but more useful than just a 500 to the user of course)
4. Move the array content to the key "root" when filename frontmatter is present

**Comment by ericroberts** [comment]
@singpolyma I think my preference is the third option: make it an error. Anything else seems like possible unexpected behaviour for the user.

**Comment by singpolyma** [comment]
sounds good to me
