### ISSUE TITLE
Can move file

### ISSUE THREAD

**Issue by ericroberts** [usetint/tint#32]

**Comment by singpolyma** [comment]
@ericroberts @jetpacksandrollerskates how do we want the UI to work here?  We have rename already, so the only thing missing is a way to move to a different folder.  Maybe a "pick up" + "put down" style move UI?  Do we want to be able to "put down" under a different name, or is move only "move between folders keeping same name" and then we keep a separate rename UI as now?

**Comment by ericroberts** [comment]
@singpolyma I think renaming would be a separate action. Otherwise the "pick up, put down" interface sounds good to me.
