### ISSUE TITLE
Show items in a collection

### ISSUE THREAD

**Issue by ericroberts** [usetint/tint#35]
Basically the same as the file UI for the collection's folder.  Maybe a nicer display of some summary metadata for each item?  (title instead of filename?)

**Comment by singpolyma** [comment]
I think we can literally link to the folder for the collection.  Why not have a nicer display all the time?  This was the thinking behind the #294 implementation putting the "add" button in the folder display context.

**Comment by ericroberts** [comment]
I also think this is sufficient for now. Closing this issue.
