### ISSUE TITLE
Login with / connect to Gitlab

### ISSUE THREAD

**Issue by ericroberts** [usetint/tint#40]
* [x] Login
* [x] Should work with self-hosted instances
* [x] Setup site config from list of repos
* [x] Auto-set-up webhook
* [x] Auto set-up deploy key (can we use deploy key? we need push access)

**Comment by singpolyma** [comment]
GitLab doesn't have read/write "deploy keys" right now... https://gitlab.com/gitlab-org/gitlab-ce/issues/19658

Should we just add our key to the user?

**Comment by ericroberts** [comment]
Sounds reasonable to me
