### ISSUE TITLE
Styles for file / folder listing page

### ISSUE THREAD

**Issue by singpolyma** [usetint/tint#67]
Includes:
- file upload
- directory creation
- file / directory rename
- file delete

**Comment by jetpacksandrollerskates** [comment]
![tint-filemanager-v1](https://cloud.githubusercontent.com/assets/2089702/17060948/361a0c3a-4ffa-11e6-804d-fc6e7f9ebd0c.png)

This just early stages. More icons and potential colour variations to come.

**Comment by singpolyma** [comment]
Do we want to show page title (from frontmatter `title`) where applicable in this view?

**Comment by singpolyma** [comment]
@jetpacksandrollerskates @ericroberts can someone slice the file/folder icons used here to SVG?
