### ISSUE TITLE
Lock access to git cache copies

### ISSUE THREAD

**Issue by ericroberts** [usetint/tint#77]
So that multiple people can use the app on the same project at once. Or even one guy in multiple tabs.

**Comment by singpolyma** [comment]
New idea: we apply each update to a fresh, temporary, clone of the repository.  This would also solve #25.  Flow would be:

1. clone to a new, temporary folder name
2. do any write+add / rm / mv
3. `git add -A .`
4. commit
5. push
  * if push fails, go to 1
