### ISSUE TITLE
Configure files to hide in .tint.yml

### ISSUE THREAD

**Issue by ericroberts** [usetint/tint#80]
Something like

    hidden_paths:
        - .*
        - Makefile

hides such files in the file browser.

**Comment by singpolyma** [comment]
Hmm. If they just use the template it's probably noise, but they might edit it to do things? The full file view is slightly advanced anyway, right? Not sure.

**Comment by singpolyma** [comment]
I think this should be configurable in `.tint.yml` -- have a list of patters to hide in the file view.

**Comment by ericroberts** [comment]
Sounds good to me.
